project_id = "nptoxwmbsxefhqjcxjhg"

[functions.neon-db]
verify_jwt = false

[functions.razorpay]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.create-staff]
verify_jwt = false
